// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgsqCKd2OovYvVyPwhLF32qyQbHYH2dsM',
    appId: '1:925010064558:web:a3653187c07e4bc7fc293f',
    messagingSenderId: '925010064558',
    projectId: 'chatapptute-27857',
    authDomain: 'chatapptute-27857.firebaseapp.com',
    storageBucket: 'chatapptute-27857.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_NiRjc86si75B8V5X9haguPj9Ykncz30',
    appId: '1:925010064558:android:5a86d033ce40d37efc293f',
    messagingSenderId: '925010064558',
    projectId: 'chatapptute-27857',
    storageBucket: 'chatapptute-27857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvcRJRhFfF2yvgdr_oQAJo_K_DHIvVRjQ',
    appId: '1:925010064558:ios:bd180daf94570c6ffc293f',
    messagingSenderId: '925010064558',
    projectId: 'chatapptute-27857',
    storageBucket: 'chatapptute-27857.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvcRJRhFfF2yvgdr_oQAJo_K_DHIvVRjQ',
    appId: '1:925010064558:ios:bd180daf94570c6ffc293f',
    messagingSenderId: '925010064558',
    projectId: 'chatapptute-27857',
    storageBucket: 'chatapptute-27857.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgsqCKd2OovYvVyPwhLF32qyQbHYH2dsM',
    appId: '1:925010064558:web:4f711019950b1fb6fc293f',
    messagingSenderId: '925010064558',
    projectId: 'chatapptute-27857',
    authDomain: 'chatapptute-27857.firebaseapp.com',
    storageBucket: 'chatapptute-27857.appspot.com',
  );
}
